### PR TITLE
Mega ED: rename mislabeled entries

### PR DESCRIPTION
**Pull request by tjanas**
This is a large commit. There were many entries (over 600) in `Mega Everdrive SMDB.txt` that did not match no-intro naming, including many with names representing a different game altogether (e.g. betas in retail folders). Many betas were duplicated as prototypes.

Some names still do not match no-intro, such as those in Game Series Collections with leading numbers in the filename for sorting. Also, the following were not changed, in order to keep entries for sequels together or to avoid confusion:

`Thunder Force IV - Lightening Force - Quest for the Darkstar (USA).md` -> `Lightening Force - Quest for the Darkstar (USA).md`

`Sensible Soccer - International Edition (Europe) (En,Fr,De,It).md` -> `International Sensible Soccer (Europe) (En,Fr,De,It).md`

`SeaQuest DSV (USA).md` -> `seaQuest DSV (USA).md`

`World of Illusion - Fushigi na Magic Box (Japan).md` -> `I Love Mickey and Donald - Fushigi na Magic Box (Japan).md`

`Mega Games 6 Vol. 3 (Europe).md` -> `Mega 6 Vol. 3 (Europe).md`

`Sylvester and Tweety in Cagey Capers (USA, Europe).md` -> `Sylvester and Tweety in Cagey Capers ~ Sylvester & Tweety in Cagey Capers (USA, Europe).md`

`Streets of Rage - Bare Knuckle - Ikari no Tekken (World) (Rev A).md` -> `Bare Knuckle - Ikari no Tekken ~ Streets of Rage (World) (Rev A).md`

`J. League Pro Striker Final Stage (Japan).md` -> `Pro Striker - Final Stage (Japan).md`

`Flux (Europe) (Beta) (Requires MegaCD) (Program).md` -> `Flux (Europe) (Beta) (Program).md`

BIOS entries not matching nointro naming were not changed.

### CODE REVIEW

**Comment by tjanas** [comment]
This also resolves https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/issues/49

**Comment by frederic-mahe** [comment]
ok, I skimmed through the changes. Do you confirm that a No-Intro vs SMDB names comparison now only returns false-positives, if any?

**Comment by tjanas** [comment]
> ok, I skimmed through the changes. Do you confirm that a No-Intro vs SMDB names comparison now only returns false-positives, if any?

Attached below are the mismatches that remain from your comparison script:
[mismatches.txt](https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/files/4565564/mismatches.txt)

**Comment by tjanas** [comment]
One entry I didn't rename that did not mention above is the following, I suspect nointro did not intend to name it _ST_ instead of _SF_

`ST II' Turbo (USA) (Proto) (Unl) (Pirate).md` <- `SF II' - Turbo (USA) (Proto) (Unl) (Pirate).md`

Also, I did not rename (my intention):
`Two Tribes - Populous II (Europe).md` <- `Populous II - Two Tribes (Europe).md`

`Toki no Keishousha - Phantasy Star III (Japan).md` <- `Phantasy Star III - Toki no Keishousha (Japan).md`

`Al Michaels Announces HardBall III (USA, Europe).md` <- `HardBall III (USA, Europe).md`

`Journey from Darkness - Strider Returns (USA).md` <- `Strider Returns - Journey from Darkness (USA).md`

**Pull request merged**
