### PR TITLE
Update ED N8 & Powerpak Hacks

### PR DESCRIPTION
**Pull request by maniac79**
** New Hacks / Updated Hacks **
- added 113 Hacks + 1 Translation from Cylum's set
- updated 18 Hack versions to match Cylcum's set [outdated versions removed]
- updated 1 Hack which was found outdated in Cylum's set (/Ultima III - Exodus Remastered (Hack) (1.07) (Adjusted font).nes)

** Clean up **
- renamed some file names to match more common naming conventions, most notably for games which have multiple hacks and were in today's update
- removed some doubles
- file names: corrected 5 instances of '.nes.nes' to '.nes'

### CODE REVIEW

**Comment by maniac79** [comment]
Wow, that was much more complex than assumed... one thing that made it more complex than assumed is that some of the Hacks I updated were in multiple places (e.g. "Selections"). I hope I was able to maintain everything correctly.

I did not add all Hacks from Cylum's set for the following reasons:

1. Some files are already in the SMDB but with different hash - no clue what to do with them.
These are the hashes for the files from Cylum's set:
f968b6ae04da37451d28d989eb9bfc12eb7e1501d9f19ba55c164acbf99df1ef	Legend of Zelda DX (Hack) (1.0).nes	22294f2ff606f90816fe0739ce3e2cbfef48e998	99290b937d1fef991740c3d562db993f	0698579d
8e0f4a239fdef0a77f678beb96c8f1412e1d5a795ba671b78b7921b23d9a63c7	Legend of Zelda Awakening of Onox (Hack) (1.0).nes	d8dc3a7eac9b858ef82233d6fb21b33c2babb2c4	c12901c75c16ec4e1bb47ce6d860c5e7	8baa6c5f
568ef7dbc736412ebb586d019b7526892f0c76571c8298c4b6604bb88e4de937	Legend of Zelda Outlands (Hack) (1.0).nes	0b93d8f2e40e085a83571409fc9973c959783a4d	135a00814899859dc90886c55dcdc4ac	4f4d295e
5299548174542e38b0b365ea5344d70b8594b62a294c729fe6389d3604df9363	Metroid Incursion (Hack) (1.1) (Mini map + save feature).nes	25cd09cc0c38a76caed5f813a588d5581e120dbc	7ed99f326a80ffa659e57bd542818135	dd6353b2
09d02eb22b6d0f147af0224296d06bceff8ea7845238ce50f30d79597f718fb9	Mighty Morphin Power Rangers (Kyouryuu Sentai ZyuRanger Translation) (1.0) (EN).nes	f147791c93684a0ddce5c2c14d2aacc2bdd0818d	915db6a2335b7c3db680af86354f8bdc	afbc9dc4
1fb2dd3d825b0f171fd68b6d3cd011e5901ced0ce9261d5c3c2697555b59ee22	Rambo First Blood Part II (P.O.W. - Prisoners of War Hack) (1.0).nes	e75c1c692c70f9f8f1af84c0e984b7f6e438b05a	d9c91081ad9069c9c1a1d02113f840c7	f1d37383
2bc279c2d3382e7a4c760822e8ea012142931fe8aea049da840f70b3fd95e620	Rockman 4 Sparking to Hero (Hack) (1.0).nes	af564ba888fda68dca45efeabeecde5142d3e42d	2c6d0f825053dfd8ebb0e16e38ed2921	99fdd00e
7d44c06ef14cd753fe11b945a812d06905920370c9483734d37acb88be997b2a	Second Ultimate Bugs Bunny Crazy Castle, The (The Bugs Bunny Crazy Castle Hack) (1.0).nes	0d0f1b62dc1acce419cd29d81a634e8f7e3cc3d3	700806e474d18479557a93802ad41223	ed29da88
3bfb9808be44b70d316106ba16b318a8a249261d7d48f4031e929428e993801f	Superman (Sunman Hack) (1.0).nes	045b89a45b93624859ab383f94a9a0a8f1e9bc52	51f79d4484e106adb5e98ed25d03a601	a3f88fd2

2. There are multiple hacks with very similar names and some of them are already in the SMDB - not sure what to make of these 2:
63937d5c878f904bf8859b00370d5cee1c821b7543e06cc9dbdacd00fbe5f876	SMB Luigi Bros. (Hack) v1.1.nes	6dd43fefbea40985faa617bfac02cb8fb8359097	d8e9c7171ba499466a0cf2b348b89b89	10c2f312
aad8c9759b828e822bcf37e93445841e664b951e5def2a9eef9ca0b58af9d897	SMB3 Mario Adventure (Hack) v1.0 [patch by DahrkDaiz Bugfix by Drakon].nes	4cb0416cb8f06430ec765e0de98b676e4183842d	326c66d832766021fcc054ae4cc4dddf	2e6d3fdc

3. This version has a higher version number already in the SMBD:
49dca919533170baca15a16fb482841d5553155f3ffc9e5adb3096ce2c995a99	Rockman 4 Minus Infinity (Hack) (1.0).nes	0379943b1e09d9f31f643a3309dbf47b82715635	85e59fec07b117cd8e8d17260612d4ee	67efe459

Following games seem to be dupes with different hashes or maybe one of them is the unpatched ROM, which in that case wouldn't belong in the Hacks folders:
83686155256233003d31cc44af232159f511d104bb41a9d142f903e895a13dc4	Super Mario Brothers Series Hacks/SMB Carnage (Hack).nes	6ee6280bf4bbdeac90b1f8d1c72137b782ca5724	d24764ab8b0f3906b9a6b15d23fdc5f6	6aa2ba1a
8e172e5c3cf5de7de53dd0bfdbe90c6666e96d7dae592bbb0815abde52158142	Super Mario Brothers Series Hacks/SMB Carnage (Hack) v1 Justin Anderson.nes	79e386c00531cd23ae61f6ee225228f005243553	c051735a0afc1720b5a6b576cd87702d	b13d8c77

1da92e5d643194d0b351c36a337014e373c179321f0602d20158be2ed8b77ffc	Contra/Super Contra X (Hack) pacnsacdave.nes	f863ab57dcfce2f3d6bb75efe0ec6dcd7bc9f597	34e10f93ab026455f54595348c1c8d6b	236e3f08
a10f5a16dc43672d935466347fde383ed7c829d29b2a9ec03fe8170ef343887e	Contra/Super Contra X (Hack).nes	2008a619582ecb71c63220d8bb557407d2ed46fa	78b84507fa76357a7c4fc1b02c686757	c4bc7460

The Contra games also show up in multiple other folders across the SMDB.
Someone else with more knowledge of the Contra hacks/unlicensed games should have a look to fix it.

Also, I had to include all my updates manually because I cannot build a complete SMDB set at the moment because I'm missing some ROMs I can't find anywhere... I would greatly appreciate if someone could help me out on this, so I can just re-scan and submit the complete SMDB for bigger updates next time for more convenience.
These games are:
Abscondee (Unl).nes	
Aether Cruisher (Unl).nes	
Aim Cruise (Unl).nes	
Amusement Park Jumping Kid (Unl).nes	
Angry Birds (Unl).nes	
Animal Contest (Unl).nes	
Blocks World (Unl).nes	
Bolide (Unl).nes	
Bolide [hM01] (Unl).nes	
Bomb Sweeper (Unl).nes	
Bug Catcher (Unl).nes	
Checkers (Unl).nes	
Contra [MMC3] (Unl).nes	
Crash Bandicoot (Unl).nes	
Depths (PD).nes	
Fairy 2001 (Unl).nes	
Fire Dragon (Unl).nes	
Fruit Gift (Unl).nes	
Happy Match (Unl).nes	
Harry Potter (Panic Restaurant) (Unl).nes	
IQ Champion (Unl).nes	
Ice Ocean (Unl).nes	
Lightning (Unl).nes	
Little Witch (Unl).nes	
Magic Egg (Unl).nes	
Man In Red (Unl).nes	
Mario Cart prg=7d0000 chr=7e0000 (Unl).nes	
Meccano (Unl).nes	
Metal Slug (Unl).nes	
Micro Mages (PD) v1 Morphcat Games.nes	
Mouse Hero (Unl).nes	
Mouse Snare (Unl).nes	
Mowing (Unl).nes	
Nature Clan Island (Unl).nes	
Nature Clan Mirror Devil World (Unl).nes	
Nature Clan Spring World (Unl).nes	
Nut Cracky (Unl).nes	
Pka Chu prg=a18000 chr=d94000 (Unl).nes	
Plants vs Zombies (Unl).nes	
Pokemon Red prg=640000 chr=620000 (Unl).nes	
Police Dog Lasy (Unl).nes	
Police vs Thief Violent Chasing (Unl).nes	
Pong Pong (Unl).nes	
Power Robot (Unl).nes	
River Jump (Unl).nes	
Rush Hour (Unl).nes	
Seaport Guarl (Unl).nes	
Seawolf (Unl).nes	
Space Base (Unl).nes	
Spider Man 2 (Unl).nes	
Star (Unl).nes	
Submarine (Unl).nes	
The Hulk (Unl).nes	
Through Man (Unl).nes	
Toy Factory (Unl).nes	
Utmost Warfare (Unl).nes	
Waddy Boy (Unl).nes	
Waddy Boy [hM65] (Unl).nes	
War Zone (Unl).nes	
Water Pipes (Unl).nes	
Wild Worm (Unl).nes	
Wonder Ball (Unl).nes

**Comment by frederic-mahe** [comment]
> Also, I had to include all my updates manually because I cannot build a complete SMDB set at the moment because I'm missing some ROMs I can't find anywhere...

Yes, hacks and unlicensed games make it hard to build a complete set. However, if you already have a partial ROM set build with the latest SMDB, you can prune the hack folder, add files to it, and parse it to make a partial SMDB. You can then use that partial SMDB to replace the corresponding section in the full SMDB.

**Comment by frederic-mahe** [comment]
Nice work @maniac79 

You may find some of the files you are looking for at https://archive.org/details/everdrive-packs

**Comment by maniac79** [comment]
Thx for the hint - not a single one from my list is in there though. ^^
Micro Mages is commercial and I have the ROM (I backed the Kickstarter) so that one is not an issue (although my hashes are different than in SMDB, think I should update this next time).

I think most if not all of the others are obscure games ripped from ancient multi-carts. And I can't find them anywhere and I've been searching 2 days straight...

**Pull request merged**
