### PR TITLE
Corrections for SMDB Packs

### PR DESCRIPTION
**Pull request by tjanas**
Addresses most of the issues presented in https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/issues/38

It does not address the variants chosen in Game Series Collections.
It does not address (Unl) [f1] roms.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
>  I believe the current SMDB standard is to use the latest revision in the main directory, with older revisions in the Revisions directory. If this is correct, other entries should be revisited.

Yes, you are correct.

> .NES file extensions changed to .nes for consistency.

Yes, a while back SmokeMonster and I tried to uniformize extensions. We replaced hundreds of odd variants, but many remain. Ideally, we should aim for a couple extensions per system: `.nes`, `.sfc`, `.n64`, `.md` and `.gen`, `.gb`, ... Nowadays, extensions are purely decorative and are only there to help people identify their files. So extensions should be informative and homogeneous.

> Did not know how to resolve the following:
```
c2441a576a7924b37003987e806720d1be9eecd29f36a56e8b1b2eb8ce3d4426	EverDrive 64/3 64DD Disk Drive/Mario Artist Talent Studio (J) T-Eng v02b LuigiBlood.n64
c2441a576a7924b37003987e806720d1be9eecd29f36a56e8b1b2eb8ce3d4426	EverDrive 64/3 64DD Disk Drive/Mario Artist Talent Studio (J) v1.2 NESWorld.z64
```
Maybe this?
```
Mario Artist Talent Studio (J) T+Eng v02b LuigiBlood 2018.n64
```
following SmokeMonster's naming scheme for translations and hacks:
- Translated name - original language name (region) T+Eng version author date
- Hack name ('source name if not obvious' hack) version author date

**Comment by frederic-mahe** [comment]
>It does not address the variants chosen in Game Series Collections.

see issue #164 

> It does not address (Unl) [f1] roms.

see issue #165

Has everything in issue #38 been addressed or moved to a new issue? I am looking forward closing that giant issue.

**Comment by frederic-mahe** [comment]
Great work @tjanas !

**Comment by tjanas** [comment]
As reported in that giant issue, the following both exist, with the expected same hash:

```
Mega EverDrive/1 US - G-P/Phantasy Star III - Generations of Doom (USA, Europe).md
Mega EverDrive/2 Europe - A-Z/1 PAL - M-R/Phantasy Star III - Generations of Doom (USA, Europe).md
```
What is the standard here? Can (USA, Europe) roms be in both locations for Genesis? I did not make a change with respect to this. That being said, I believe everything else in the large issue has been fixed besides those revisited in issues 164 and 165.

**Comment by frederic-mahe** [comment]
In my opinion it is ok if `Phantasy Star III - Generations of Doom (USA, Europe)` appears in both the US and Europe folders.

It would be wrong if both of them had different names `(USA)` and `(Europe)`, as it would implied they are different games. Everdrives store saves and save states using file names, here the filenames are the same, so there is no ambiguity for users: the PAL and US NTSC releases are the exact same game.

If that makes sense, I suggest to keep the two copies of Phantasy Star III, we'll see if we find other cases that force us to think differently.

**Comment by frederic-mahe** [comment]
@tjanas I created a Wiki entry with some guidelines https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/wiki/Guidelines-for-SMDB-creators

Maybe we can establish rules as we go?

**Comment by tjanas** [comment]
I agree.

**Pull request merged**
