### PR TITLE
Some more N64 cleanup

### PR DESCRIPTION
**Pull request by Drakonas**
1. Remove duplicate `Yoshi's Story (U) (M2) [!] D-Pad Controls.z64` rom from the GSC `Miscellaneous/D-Pad Controls/D-Pad Control (Natively)` folder. It is a hack, not native, and already exists in the SubDrag patches folder. I assume it was accidentally copied at some point.
2. I previously moved `GameBooster 64 (Europe) (v1.1) (Unl).z64` to the Unlicensed folder. I didn't stop to think it's supposed to go with the other one for USA that exists in the `5 Tools & Service Test Carts` folder. It has been moved there now.
~~3. Updated `Puyo Puyo Sun 64`, `Densha de Go! 64`, and `Virtual Pro Wrestling 2` in the GSC folder with their English translations. I believe this should cover all translations being replaced in Game Series Collections.~~ This has been reverted. Under review as the romhacks are outdated.
3. Jet Force Gemini had an improper number for the Retro-Sanctuary Best Of list. I confirmed on the [actual site](http://retro-sanctuary.com/Top-100-N64-Games-Page-7.html).

All roms already exist in the pack, so no new roms should be needed.

### CODE REVIEW

**Comment by tjanas** [comment]
@Drakonas Does this have a known version and author? Virtual Pro Wrestling 2 (J) T-Eng

**Comment by tjanas** [comment]
Also, is there a version for this?

Puyo Puyo Sun 64 - English (J) T+Eng Zoinkity

**Comment by Drakonas** [comment]
I'll look into that. And there is one more commit I need to add before this gets merged.

**Comment by Drakonas** [comment]
These roms already exist in the `4 Translations` folder, which is where I got them from. Seems to be another improperly patched romhack, or it is 1.0 version. Current is 1.1. The Virtual Pro Wrestling 2 seems to be the beta 2 version. The latest is beta 3. I'll add that to my notes to have it included. I guess I can actually hold off on that then... hmm. Can a commit be removed from a PR? Or does the entire PR have to be cancelled?

Sources: https://www.romhacking.net/translations/5470/
https://www.tapatalk.com/groups/vpw2dojo/english-patch-t336.html

**Comment by Drakonas** [comment]
I see how to revert a branch to an earlier commit. I'll go ahead and do that. I'll save additional roms for another PR.

**Comment by Drakonas** [comment]
Also, the `Densha de Go! 64` translation has had an update since being added. I'd rather keep new roms in their own PR's, but tell me what you think.

**Comment by Drakonas** [comment]
Please hold while I get one more commit pushed. I missed something.

**Comment by Drakonas** [comment]
Alright. I'll update the OP with the actual changes.

**Comment by Drakonas** [comment]
Would you rather me just create a new PR? lol.

**Comment by tjanas** [comment]
I'll close this. You can reopen it later after everything's all good (you can squash your commits in your feature branch if you want before reopening).

**Comment by Drakonas** [comment]
Didn't realize you can do that. Thanks.

**Pull request closed without merging**
