### PR TITLE
N64 Translation Updates

### PR DESCRIPTION
**Pull request by Drakonas**
1. Remove `4 Hacks/Densha de Go! 64 English Localization (J) T+Eng v1 Zoinkity.z64`. This is a translation, and is a duplicate.
2. Remove `4 Translations/Animal Crossing (J) English T-Eng.z64`. The hash is unrecognized, but the only currently known translation (by Zoinkity) is in the pack, and only had one release, so this is probably a badly patched rom from a poor source. The patching did originally require extending the rom size prior to patching. This step may have been missed originally.
3. Rename roms to properly match the naming scheme listed in the wiki, as well as update to the names that match the translation's pages.
        Note: Doubutsu no Mori is literally translated to `Animal Forest`. While the name was transliterated to Animal Crossing when the game released outside of Japan on the Gamecube (as `Animal Crossing e+`), this name wasn't officially created yet during the N64's lifetime. Thus, Zoinkity opted to name the rom `Animal Forest` on the title screen and in the [ROMHacking page](https://www.romhacking.net/translations/1581/).
4. Update all outdated translations in the `4 Translations` folder.
        Sources:
        [Densha de Go! 64](https://www.romhacking.net/translations/2947/)
        [Mario Artist 64DD roms](https://64dd.org/translations.html)
        [Puyo Puyo Sun 64](https://www.romhacking.net/translations/5470/)
        [Sim City 64 ozidual](http://krikzz.com/forum/index.php?topic=6982.0)
        [Sim City 64 PeterLemon](https://github.com/PeterLemon/N64/blob/master/Translate/SimCity-64/NUD-DSCJ-JPN.n64.xdelta3) (Rename to xdelta to use) Note: PeterLemon's changes were forwarded to the VWF build by ozidual the same day as PeterLemon (aka krom) updated his GitHub. ozidual's page states it utilizes krom's developments for the "initial translation", so it's safe to say that the update on krom's GitHub prompted ozidual to forward the new translations to 0.6.38. (I'd expect ozidual was notified prior to the actual commit by krom, so they could release close to the same time, but this is just an assumption) I left both in, because they may have separate purposes. Not entirely sure what VWF is. We can leave this up for review later, but it is now updated.
        [Virtual Pro Wrestling 2](https://www.tapatalk.com/groups/vpw2dojo/english-patch-t336.html) Note: Info on credited creators found in the introduction of the VPW2 freem hack [here](http://vpw.ajworld.net/vpw2freem/Manual/index.html#intro).
5. Distribute all updated translations, both renamed and replaced, to `3 64DD Disk Drive` and `4 Game Series Collection`)
        Extra note: `4 Game Series Collections/Best-Of Lists/V's Recommended Games - 4chan/64DD Disc Drive` had the clean dump of Mario Artist Polygon Studio, but did not have the translated version. This was added.
6. `3 64DD Disk Drive` folder seems to be missing the clean dump of Mario Artist Talent Studio v1.2. It had only the translation.
7. Discussed in Discord for a while. Fixed the name for Virtual Pro Wrestling 2.

Verified my pack against the SMDB every step of the way.

I tested all 7 new roms on my 64Drive. All of them boot:
```
Densha de Go! 64 (J) T+Eng v1.01 Zoinkity.z64
Mario Artist - Paint Studio (J) T+Eng v2.1 LuigiBlood.n64
Mario Artist - Talent Studio (J) T-Eng v2b LuigiBlood.n64
Puyo Puyo Sun 64 (J) T+Eng v1.1 Zoinkity.z64
Sim City 64 (J) T-Eng PeterLemon 2017-11-01.n64
Sim City 64 (J) T-Eng VWF 0.6.38 ozidual.n64
Virtual Pro Wrestling 2 - Oudou Keishou (J) T-Eng beta3 S.K. Stylez 2015-01-17.z64

### CODE REVIEW

**Comment by Drakonas** [comment]
I added a commit to fix my incorrect naming of `Virtual Pro Wrestling 2 - Oudou Keishou (J) T-Eng beta3 S.K. Stylez 2015-01-17.z64`. This should now be fixed.

**Comment by frederic-mahe** [comment]
Nice work!

**Comment by tjanas** [comment]
@Drakonas can you provide the source file information that should be used with the xdelta patch for `Sim City 64 (J) T-Eng PeterLemon 2017-11-01.n64`?

**Comment by Drakonas** [comment]
> @Drakonas can you provide the source file information that should be used with the xdelta patch for `Sim City 64 (J) T-Eng PeterLemon 2017-11-01.n64`?

It requires the v1.1 that is NOT Clean OZ Fixed RTC. So the original dump.

**Pull request merged**
