### PR TITLE
NES: Update ED N8 & PowerPak SMDB

### PR DESCRIPTION
**Pull request by maniac79**
**Game Series Collection**
Main updates:
- Updated Hashes to match No-Intro where required.
- Changed filenames to match No-Intro or file names from other folders (e.g. Hacks, Translations)
- Removed games from 'Japan (Not yet translated)' which actually have a translation.
- Replaced some bad Good ROM hashes by No-Intro hashes
- Updated Top lists (some games were missing or ranking has changed).

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Patch only touches the _Game Series Collections_, good:
```
# addition
    104 4 Game Series Collections/Accesories & Add-Ons
    808 4 Game Series Collections/Best-Of Lists
    655 4 Game Series Collections/Developer
    270 4 Game Series Collections/Franchise
   1548 4 Game Series Collections/Genre
    325 4 Game Series Collections/Miscellaneous
    153 4 Game Series Collections/Multiplayer
   1128 4 Game Series Collections/Regions
# deletion
    107 4 Game Series Collections/Accesories & Add-Ons
    830 4 Game Series Collections/Best-Of Lists
    729 4 Game Series Collections/Chronological
    724 4 Game Series Collections/Developer
    270 4 Game Series Collections/Franchise
   1520 4 Game Series Collections/Genre
    458 4 Game Series Collections/Miscellaneous
    166 4 Game Series Collections/Multiplayer
```

`Chronological`, `Miscellaneous/2 Player Co-Op` are gone, as agreed with @tjstogy. I am going to merge that pull request. @maniac79 the next step is to converge with [tjstogy's latest layout](https://github.com/tjanas/EverDrive-Packs-Lists-Database/commit/faaaa612cdba03554070d7e70dded6b586f19496).

I wrote some code to compare folder layouts. Please review the differences and submit new patches if need be. If you think you should diverge from tjstogy's layout, please explain why:
```sh
MANIAC="/tmp/EverDrive-Packs-Lists-Database/EverDrive Pack SMDBs/EverDrive N8 & PowerPak SMDB.txt"
TJSTOGY="/tmp/tjstogy/EverDrive N8 & PowerPak SMDB.txt"

function list_GSC_folders() {
    cut -f 2 "${1}" | \
        sed 's/\/[^/]*$/\//' | \
        uniq | \
        grep "Game Series" | \
        sed 's/EverDrive N8\/4 Game Series Collections\///' | \
        sort
}

# Game Series Collections folders present in tjstogy and missing or
# renamed in maniac
comm -23 \
     <(list_GSC_folders "${TJSTOGY}") \
     <(list_GSC_folders "${MANIAC}")

# Game Series Collections folders present in maniac and missing or
# renamed in tjstogy
comm -23 \
     <(list_GSC_folders "${MANIAC}") \
     <(list_GSC_folders "${TJSTOGY}")
```

*folders present in tjstogy and missing or renamed in maniac*
```
Best-Of Lists/Best Beat 'em Ups - Reddit/
Best-Of Lists/Most Expensive Games - PriceCharting.com/
Best-Of Lists/Top 10 Puzzle Games - GameRant/
Best-Of Lists/Top 10 Puzzle Games - VideoChums.com/
Best-Of Lists/Top 10 RPG's - TheOldSchoolGameVault/
Best-Of Lists/Top 10 Sports Games - BleacherReport.com/
Best-Of Lists/Top 10 Strategy Games - Ranker/
Best-Of Lists/Top 10 Zapper Games - Ranker/
Best-Of Lists/Top 20 Arcade Games - Ranker/
Best-Of Lists/Top 20 Puzzle Games - Ranker/
Best-Of Lists/Top 20 Sports Games - Ranker.com/
Controllers & Peripherals/Controllers - Arkanoid Vaus/
Controllers & Peripherals/Controllers - Famicom Exclusives/4 Players Adaptor/
Controllers & Peripherals/Controllers - Famicom Exclusives/Bandai Hyper Shot Light Gun/
Controllers & Peripherals/Controllers - Famicom Exclusives/Bandai Oeka Kids Drawing Tablet/
Controllers & Peripherals/Controllers - Famicom Exclusives/Capcom Mahjong Keypads/
Controllers & Peripherals/Controllers - Famicom Exclusives/Coconuts Pachinko Controller/
Controllers & Peripherals/Controllers - Famicom Exclusives/Famicom 3D System/
Controllers & Peripherals/Controllers - Famicom Exclusives/Famicom 3D System/Japan (Not Yet Translated)/
Controllers & Peripherals/Controllers - Famicom Exclusives/Famicom Microphone (Controller 2)/
Controllers & Peripherals/Controllers - Famicom Exclusives/Famicom Microphone (Controller 2)/English Translations/
Controllers & Peripherals/Controllers - Famicom Exclusives/Hori Track/
Controllers & Peripherals/Controllers - Famicom Exclusives/Konami Exciting Boxing/
Controllers & Peripherals/Controllers - Famicom Exclusives/Konami Hyper Shot/
Controllers & Peripherals/Controllers - Famicom Exclusives/Konami Top Rider Bike Controller/
Controllers & Peripherals/Controllers - Famicom Exclusives/Nichibutsu Crazy Climber Sticks/
Controllers & Peripherals/Controllers - Famicom Exclusives/Party Room 21 Controller/
Controllers & Peripherals/Controllers - Famicom Exclusives/Pokkun Mogura/
Controllers & Peripherals/Controllers - Famicom Exclusives/Sunsoft Barcode World Reader/
Controllers & Peripherals/Controllers - Four Score Multitap/
Controllers & Peripherals/Controllers - Other/3D Glasses (Anaglyph Red Blue)/
Controllers & Peripherals/Controllers - Other/Aladdin Deck Enhancer/
Controllers & Peripherals/Controllers - Other/Konami LaserScope/
Controllers & Peripherals/Controllers - Other/Miracle Piano Keyboard/
Controllers & Peripherals/Controllers - Other/Racermate Challenge II Bicycle Trainer/
Controllers & Peripherals/Controllers - Other/U-Force/
Controllers & Peripherals/Controllers - Power Glove/
Controllers & Peripherals/Controllers - Power Pad/
Controllers & Peripherals/Controllers - Power Pad/Japan (Not Yet Translated)/
Controllers & Peripherals/Controllers - R.O.B. The Robot/
Controllers & Peripherals/Controllers - Zapper Light Gun/1 All Zapper Games/
Controllers & Peripherals/Controllers - Zapper Light Gun/2 Best Of Lists/Top 10 Zapper Games - Ranker/
Developer/Developer HAL Laboratory/
Developer/Developer Konami/
Developer/Unlicensed Developers/Tengen/Broken/
Franchise/Castlevania/
Franchise/Contra/
Franchise/Donkey Kong/
Franchise/Looney Tunes (Warner Bros)/
Franchise/Ninja Gaiden/
Franchise/Teenage Mutant Ninja Turtles/
Franchise/The Simpsons/
Franchise/TV Show Based/Sort By - Cartoons/
Franchise/TV Show Based/Sort By - Other/
Genre/Action Adventure/1 All Action Adventure Games/
Genre/Action Adventure/2 Sort By Game Type/Action Adventure - General/
Genre/Action Adventure/2 Sort By Game Type/Action Adventure - Linear/
Genre/Action Adventure/2 Sort By Game Type/Action Adventure - Open World/
Genre/Action Adventure/2 Sort By Game Type/Action Adventure - Survival/
Genre/Action Adventure/3 Canceled & Unreleased/
Genre/Adventure/1 All Adventure Games/
Genre/Adventure/2 Sort By Game Type/Adventure - 3D/
Genre/Adventure/2 Sort By Game Type/Adventure - General/
Genre/Adventure/2 Sort By Game Type/Adventure - Point & Click/
Genre/Adventure/2 Sort By Game Type/Adventure - Visual Novel/
Genre/Arcade/
Genre/Beat 'em Up/1 All Beat 'em Up Games/
Genre/Beat 'em Up/2 Japan Exclusives/
Genre/Beat 'em Up/3 Best Of Lists/Best Beat 'em Ups - Reddit/
Genre/Casino/
Genre/Compilation/
Genre/Compilation/Action 52/
Genre/Fighting/1 All Fighting Games/
Genre/Fighting/3 Canceled & Unreleased/
Genre/Fighting/3 Regional Exclusives/
Genre/Light Gun/1 All Zapper Light Gun Games/
Genre/Light Gun/2 Best Of Lists/Top 10 Zapper Games - Ranker/
Genre/Pinball/1 All Pinball Games/
Genre/Pinball/2 Hacks/
Genre/Platformers/1 All Platformers/
Genre/Platformers/2 Best Of Lists/5 Platformers You Missed - TheNerdy/
Genre/Platformers/2 Best Of Lists/Top 10 Platformers - ArcadeSushi.com/
Genre/Platformers/2 Best Of Lists/Top 10 Platformers - Cygnus Destroyer (YouTube)/
Genre/Platformers/2 Best Of Lists/Top 10 Underrated Action Platformers - 8bitcity/
Genre/Platformers/2 Best Of Lists/Top 10 Underrated Action Platformers - 8bitcity/Additions by AtariAge Forum/
Genre/Platformers/3 Canceled & Unreleased/
Genre/Puzzle/1 All Puzzle Games/
Genre/Puzzle/2 Sort By Game Type/Puzzle - Action/
Genre/Puzzle/2 Sort By Game Type/Puzzle - General/
Genre/Puzzle/2 Sort By Game Type/Puzzle - Hidden Object/
Genre/Puzzle/2 Sort By Game Type/Puzzle - Matching/
Genre/Puzzle/2 Sort By Game Type/Puzzle - Stacking/
Genre/Puzzle/3 Best Of Lists/Top 10 Puzzle Games - GameRant/
Genre/Puzzle/3 Best Of Lists/Top 10 Puzzle Games - VideoChums.com/
Genre/Puzzle/3 Best Of Lists/Top 20 Puzzle Games - Ranker/
Genre/Puzzle/3 Canceled & Unreleased/
Genre/Racing/1 All Racing Games/
Genre/Racing/2 Multiplayer/
Genre/Racing/2 Sort By Game Type/Racing - Arcade Style/
Genre/Racing/2 Sort By Game Type/Racing - Simulation Style/
Genre/Racing/3 Canceled and Unreleased/
Genre/Racing/3 Japan Exclusives/
Genre/Role Playing Games/1 All Role Playing Games/
Genre/Role Playing Games/2 Sort By Game Type/RPG - Action/
Genre/Role Playing Games/2 Sort By Game Type/RPG - General/
Genre/Role Playing Games/2 Sort By Game Type/RPG - Japanese Style/
Genre/Role Playing Games/2 Sort By Game Type/RPG - Western Style/
Genre/Role Playing Games/3 Best Of Lists/Top 10 RPG's - Ranker.com/
Genre/Role Playing Games/3 Best Of Lists/Top 10 RPG's - TheOldSchoolGameVault/
Genre/Run 'n' Gun/1 All Run 'n' Gun Games/
Genre/Run 'n' Gun/2 Sort By Game Type/Run 'n' Gun - Side-Scrolling View/
Genre/Run 'n' Gun/2 Sort By Game Type/Run 'n' Gun - Top Down View/
Genre/Shoot 'em Up/1 All Shoot 'em Up Games/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - Hacks/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - Homebrew/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/Type - Shooter Elements/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - 3D/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - Fixed-Screen/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - Free Roam & Collect 'Em Up/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - Horizontal Scrolling/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - Hybrid (Vertical & Horizontal)/
Genre/Shoot 'em Up/2 Sort By Game Type/Shoot 'em Ups - View & Type/View - Vertical Scrolling/
Genre/Shoot 'em Up/3 Best Of Lists/Best Shoot 'em Ups - Retro-Sanctuary.com/
Genre/Shoot 'em Up/3 Best Of Lists/Top 10 Auto-Scrolling Shmups - GameFaqs.com/
Genre/Shoot 'em Up/3 Best Of Lists/Top 10 Auto-Scrolling Shmups - GameFaqs.com/Honorable Mentions/
Genre/Shoot 'em Up/3 Canceled & Unreleased/
Genre/Simulation/1 All Simulation Games/
Genre/Simulation/2 Sort By Game Type/Simulation - Flight/
Genre/Simulation/2 Sort By Game Type/Simulation - Marine/
Genre/Simulation/2 Sort By Game Type/Simulation - Space/
Genre/Simulation/2 Sort By Game Type/Simulation - Vehicle/
Genre/Sports/1 All Sports Games/
Genre/Sports/2 Sort By Sport Type/Sports - Athletics/
Genre/Sports/2 Sort By Sport Type/Sports - Baseball/
Genre/Sports/2 Sort By Sport Type/Sports - Basketball/
Genre/Sports/2 Sort By Sport Type/Sports - Billiards/
Genre/Sports/2 Sort By Sport Type/Sports - Bowling/
Genre/Sports/2 Sort By Sport Type/Sports - Boxing/
Genre/Sports/2 Sort By Sport Type/Sports - Fishing/
Genre/Sports/2 Sort By Sport Type/Sports - Football (American)/
Genre/Sports/2 Sort By Sport Type/Sports - Golf/
Genre/Sports/2 Sort By Sport Type/Sports - Hockey/
Genre/Sports/2 Sort By Sport Type/Sports - Other/
Genre/Sports/2 Sort By Sport Type/Sports - Skateboarding/
Genre/Sports/2 Sort By Sport Type/Sports - Skiing & Snowboarding/
Genre/Sports/2 Sort By Sport Type/Sports - Soccer/
Genre/Sports/2 Sort By Sport Type/Sports - Tennis/
Genre/Sports/2 Sort By Sport Type/Sports - Volleyball/
Genre/Sports/2 Sort By Sport Type/Sports - Wrestling/
Genre/Sports/3 Best Of Lists/Top 10 Sports Games - BleacherReport.com/
Genre/Sports/3 Best Of Lists/Top 10 Sports Games - GameFAQs.com/
Genre/Sports/3 Best Of Lists/Top 20 Sports Games - Ranker.com/
Genre/Sports/3 Canceled & Unreleased/
Genre/Strategy/1 All Strategy Games/
Genre/Strategy/2 Sort By Game Type/Strategy - General/
Genre/Strategy/2 Sort By Game Type/Strategy - Management/
Genre/Strategy/2 Sort By Game Type/Strategy - Real Time/
Genre/Strategy/2 Sort By Game Type/Strategy - Turn Based/
Genre/Strategy/3 Best Of Lists/Top 10 Strategy Games - Ranker/
Genre/Strategy/3 Canceled & Unreleased/
Miscellaneous/Canceled & Unreleased/
Miscellaneous/De-Censored/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/3-D WorldRunner/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Adventures of Lolo/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Bases Loaded/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Bases Loaded 2/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Bases Loaded 3/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Bases Loaded 4/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Castlevania II/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Castlevania III Dracula's Curse/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Dance Aerobics/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Double Dribble/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Excitebike/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Golf/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Gyruss/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Kid Icarus/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Mario Bros/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Metroid/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Mr. Gimmick/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Mystery Quest/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/NES Open Tournament Golf/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Rad Racket/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Rolling Thunder/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/The Legend of Zelda/
Miscellaneous/Expansion Audio Support/Exp Audio - Comparisons/Zelda II Adventure of Link/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/All Exp Audio Games (English)/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Konami VRC6/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Konami VRC7/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Namco 163/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Nintendo FDS/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Nintendo MMC5/
Miscellaneous/Expansion Audio Support/Exp Audio - English Friendly/Sort By Sound Chip/Sunsoft 5B/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/All Exp. Audio Games (Japan)/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Konami VRC6/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Konami VRC7/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Mitsubishi M50805/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Namco 163/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/NEC D7755/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/NEC D7756/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Nintendo FDS/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Nintendo MMC5/
Miscellaneous/Expansion Audio Support/Exp Audio - Japan (Originals)/Sort By Sound Chip/Sunsoft 5B/
Miscellaneous/Halloween Time/
Miscellaneous/Ported Games/Ports - Arcade Based/
Miscellaneous/Ported Games/Ports - PC Based/
Miscellaneous/Regional Exclusives/Exclusives - Japan (English)/
Miscellaneous/Regional Exclusives/Exclusives - PAL/PAL Exclusives - Licensed/
Miscellaneous/Regional Exclusives/Exclusives - PAL/PAL Exclusives - Unlicensed/
Miscellaneous/Re-Releases/Gamecube (Animal Crossing)/
Miscellaneous/Re-Releases/GBA (E-Reader)/
Miscellaneous/Re-Releases/Nintendo Classic Mini 2016/Classic Mini - Famicom/Famicom Mini - Regular Edition/Famicom Mini - Originals/
Miscellaneous/Re-Releases/Nintendo Classic Mini 2016/Classic Mini - Famicom/Famicom Mini - Shonen Jump Edition/Famicom Shonen Jump - English/
Miscellaneous/Re-Releases/Nintendo Classic Mini 2016/Classic Mini - Famicom/Famicom Mini - Shonen Jump Edition/Famicom Shonen Jump - Originals/
Miscellaneous/Re-Releases/Nintendo Classic Mini 2016/Classic Mini - NES/
Miscellaneous/X-Rated/
Multiplayer/Multiplayer - 2 Player Co-Op/
Multiplayer/Multiplayer - 2 Player Co-Op/Top 10 Co-Op Games - GameFAQs.com/
Multiplayer/Multiplayer - Best Of Lists/Top 10 Co-Op Games - CousinGaming.com/
Multiplayer/Multiplayer - Best Of Lists/Top 10 Co-Op Games - DKOldies.com/
Multiplayer/Multiplayer - Best Of Lists/Top 10 Co-Op Games - GameFAQs.com/
Multiplayer/Multiplayer - Best Of Lists/Top 10 Multiplayer Games - WatchMojo.com/
Multiplayer/Multiplayer - Best Of Lists/Top 10 Multiplayer Games - WatchMojo.com/Honorable Mentions/
Multiplayer/Multiplayer - Four Score Multitap/
```

*folders present in maniac and missing or renamed in tjstogy*
```
Accesories & Add-Ons/Famicom 3D System/
Accesories & Add-Ons/Famicom 3D System/Japan (Not Yet Translated)/
Accesories & Add-Ons/Light Gun Zapper/
Accesories & Add-Ons/Light Gun Zapper/Duck Hunt Based Unlicensed/
Accesories & Add-Ons/Light Gun Zapper/Hogan's AlleyBased Unlicensed/
Accesories & Add-Ons/Light Gun Zapper/Wild Gunman Based Unlicensed/
Accesories & Add-Ons/Microphone Support (Controller 2)/
Accesories & Add-Ons/Microphone Support (Controller 2)/English Translations/
Accesories & Add-Ons/Multitap (1-4+ Players)/
Accesories & Add-Ons/Multitap (1-4+ Players)/Japan (not yet translated)/
Accesories & Add-Ons/Multitap (1-4+ Players)/PD/
Accesories & Add-Ons/Power Pad/
Accesories & Add-Ons/Power Pad/Japan (Not Yet Translated)/
Accesories & Add-Ons/R.O.B. The Robot/
Accesories & Add-Ons/Vaus Arkanoid Controller/
Best-Of Lists/Most Expensive Games (2017) - PriceCharting.com/
Best-Of Lists/Top 10 Sports Games - Ranker.com/
Best-Of Lists/V's Recommended Games - 4chan/Famicom/
Best-Of Lists/V's Recommended Games - 4chan/Famicom Disk System/
Best-Of Lists/V's Recommended Games - 4chan/Hacks/
Best-Of Lists/V's Recommended Games - 4chan/NES/
Best-Of Lists/V's Recommended Games - 4chan/NES/Japan (Not Yet Translated)/
Developer/Developer HAL/
Developer/Developer Konami - Ultra/
Franchise/TV Show Based/Sort By - Cartoon/
Franchise/TV Show Based/Sort By - Disney/
Franchise/TV Show Based/Sort By - Looney Tunes (Warner Bros)/
Franchise/TV Show Based/Sort By - Non Cartoon/
Franchise/TV Show Based/Sort By - Teenage Mutant Ninja Turtles/
Franchise/TV Show Based/Sort By - The Simpsons/
Genre/Action Adventure/All Action Adventure/
Genre/Action Adventure/Sort By - General/
Genre/Action Adventure/Sort By - Linear/
Genre/Action Adventure/Sort By - Open World/
Genre/Action Adventure/Sort By - Survival/
Genre/Adventure/All Adventure/
Genre/Adventure/Sort By - 3D/
Genre/Adventure/Sort By - General/
Genre/Adventure/Sort By - Point & Click/
Genre/Adventure/Sort By - Visual Novel/
Genre/Beat 'em Up/
Genre/Beat 'em Up/Japan (Not Yet Translated)/
Genre/Fighters (1v1)/
Genre/Fighters (1v1)/Japan (Not Yet Translated)/
Genre/Gambling/
Genre/Light Gun Zapper/
Genre/Light Gun Zapper/Duck Hunt Based Unlicensed/
Genre/Light Gun Zapper/Hogan's AlleyBased Unlicensed/
Genre/Light Gun Zapper/Wild Gunman Based Unlicensed/
Genre/Pinball/
Genre/Platformers/
Genre/Puzzle/All Puzzle/
Genre/Puzzle/Sort By - Action/
Genre/Puzzle/Sort By - General/
Genre/Puzzle/Sort By - Hidden Object/
Genre/Puzzle/Sort By - Matching/
Genre/Puzzle/Sort By - Stacking/
Genre/Racing/All Racing/
Genre/Racing/Sort By - 1-2+ Players/
Genre/Racing/Sort By - 1 Player Only/
Genre/Role Playing Games/All Role Playing Games/
Genre/Role Playing Games/Sort By - Action RPG/
Genre/Role Playing Games/Sort By - General RPG/
Genre/Role Playing Games/Sort By - Japanese Style RPG/
Genre/Role Playing Games/Sort By - Western Style RPG/
Genre/Run 'n Gun/All Run 'n Guns/
Genre/Run 'n Gun/Sort By - Overhead/
Genre/Run 'n Gun/Sort By - Sidescrolling/
Genre/Shoot 'em Up/All Shoot 'em Ups/
Genre/Shoot 'em Up/Sort By - Hacks/
Genre/Shoot 'em Up/Sort By - Homebrew/
Genre/Shoot 'em Up/Sort By - View & Type/Type - Shooter Elements/
Genre/Shoot 'em Up/Sort By - View & Type/View - 3D/
Genre/Shoot 'em Up/Sort By - View & Type/View - Fixed-Screen/
Genre/Shoot 'em Up/Sort By - View & Type/View - Free Roam & Collect 'Em Up/
Genre/Shoot 'em Up/Sort By - View & Type/View - Horizontal Scrolling/
Genre/Shoot 'em Up/Sort By - View & Type/View - Hybrid (Vertical & Horizontal)/
Genre/Shoot 'em Up/Sort By - View & Type/View - Vertical Scrolling/
Genre/Simulation/All Simulation/
Genre/Simulation/Sort By - Flight/
Genre/Simulation/Sort By - Marine/
Genre/Simulation/Sort By - Space/
Genre/Simulation/Sort By - Vehicle/
Genre/Sports/Athletics/
Genre/Sports/Baseball/
Genre/Sports/Basketball/
Genre/Sports/Billiards/
Genre/Sports/Boxing/
Genre/Sports/Fishing/
Genre/Sports/Football (American)/
Genre/Sports/Golf/
Genre/Sports/Hockey/
Genre/Sports/Other Sports/
Genre/Sports/Skateboarding/
Genre/Sports/Skiing & Snowboarding/
Genre/Sports/Soccer/
Genre/Sports/Tennis/
Genre/Sports/Volleyball/
Genre/Sports/Wrestling/
Genre/Strategy/All Strategy/
Genre/Strategy/Sort By - General/
Genre/Strategy/Sort By - Management/
Genre/Strategy/Sort By - Real Time/
Genre/Strategy/Sort By - Turn Based/
Miscellaneous/Erotic/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - English Translated/Konami VRC6/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - English Translated/Konami VRC7/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - English Translated/Namco 163/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - English Translated/Nintendo FDS/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - English Translated/Sunsoft 5B/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Konami VRC6/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Konami VRC7/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Mitsubishi M50805/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Namco 163/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/NEC D7756/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Nintendo FDS/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Nintendo MMC5/
Miscellaneous/Famicom Expansion Audio Supported/Sort By Audio Chip - Japan Originals/Sunsoft 5B/
Miscellaneous/Halloween Games/
Miscellaneous/Nintendo Black Box Games/
Miscellaneous/Nintendo Classic Mini 2016 Pack-ins/Nintendo Classic Mini/
Miscellaneous/Nintendo Classic Mini 2016 Pack-ins/Nintendo Classic Mini Famicom/
Miscellaneous/Ported Games/Arcade Ports/
Miscellaneous/Ported Games/PC Ports/
Miscellaneous/Uncensored/
Multiplayer/Sort By - 2 Player Co-Op/
Multiplayer/Sort By - Best Of Lists/Top 10 Co-Op Games - CousinGaming.com/
Multiplayer/Sort By - Best Of Lists/Top 10 Co-Op Games - DKOldies.com/
Multiplayer/Sort By - Best Of Lists/Top 10 Co-Op Games - GameFAQs.com/
Multiplayer/Sort By - Best Of Lists/Top 10 Multiplayer Games - WatchMojo.com/
Multiplayer/Sort By - Best Of Lists/Top 10 Multiplayer Games - WatchMojo.com/Honorable Mentions/
Multiplayer/Sort By - Multitap (1-4 Player)/
Multiplayer/Sort By - Multitap (1-4 Player)/PD/
Regions/1 PAL A/
Regions/1 PAL B/
Regions/2 PAL A, not in PAL B/
Regions/2 PAL B, not in PAL A/
Regions/3 PAL, not in US/
Regions/3 US, not in Europe/
```

**Comment by tjstogy** [comment]
Many of these differences are simply because maniac was working from my 3 year old outdated Game Series Collections, which is currently present in the SMDB. I'd suggest we work on pushing my updated Game Series Collections, and then any changes he would like to present can be done from there. It will certainly minimize this list almost completely.

**Comment by tjstogy** [comment]
>     * Updated Hashes to match No-Intro where required.

Instead of focusing on matching No-Intro, it should simply match whatever is in the latest Smokemonster A-Z pack, unless we are aiming to match No-Intro universally. There should be no unique roms in the Game Series Collections.

>     * Changed filenames to match No-Intro or file names from other folders (e.g. Hacks, Translations)

See above.

>     * Removed games from 'Japan (Not yet translated)' which actually have a translation.

This is helpful, please consider doing this again based on my UPDATED pack and submit separately.

>     * Replaced some bad Good ROM hashes by No-Intro hashes

Again, please match whatever our common goal is here. 

>     * Updated Top lists (some games were missing or ranking has changed).

Already done in my updated list.

**Comment by maniac79** [comment]
> Instead of focusing on matching No-Intro, it should simply match whatever is in the latest Smokemonster A-Z pack, unless we are aiming to match No-Intro universally. There should be no unique roms in the Game Series Collections.

Agreed for Hacks/Translations, etc...
But I believe it makes more sense to use the No-Intro ROMs for unmodified games. I don't know how to ensure we're using working/legit ROMs otherwise. Don't you think?

@frederic-mahe:
I see the PR was merged, is there anything left for me to do at this stage?

**Pull request merged**
