### PR TITLE
MiSTer Pack: Many fixes

### PR DESCRIPTION
**Pull request by SmokeMonsterPacks**
- Removed depreciated /bootroms folder
- Moved/renamed all boot.roms and placed in parent folders
- /backgrounds renamed /wallpapers 
- Update Apple.II.4am.2020-05-19
- Add PC88 boot.rom
- Add X68000 boot.rom
- Add Autoboot PCE CD BIOS
- ht1080z renamed trs-80
- many fixes

### CODE REVIEW

**Comment by frederic-mahe** [comment]
@SmokeMonsterPacks I see you include the 'script' folder in the pack. Is this intended? (just checking)

**Comment by SmokeMonsterPacks** [comment]
The root folder, /Scripts shouldn't have changed if that's the one you're referring to.

**Comment by frederic-mahe** [comment]
I was referring to the three changes your commits makes in `MiSTer/Scripts/`, but that's really minor.

**Comment by SmokeMonsterPacks** [comment]
Yes, those are good

**Pull request merged**
