### PR TITLE
GUI for parse_pack and build_pack Python scripts

### PR DESCRIPTION
**Pull request by Aleyr**
I created a UI based on Python tkinter, since Python 3 is requirement and tkinter comes included this should not change the minimum requirements.

Changes made to parse_pack and build_pack are mostly PEP related ones, there's however one change, I extracted the print to stdout into a function since it was the same code in two places, I also removed the end="\r" parameter since it messed up with the way I was reading updates on the subprocess from the UI.

I'll test my script on Linux/MAC on the following days, but wanted to create this request to let you guys know about my project.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Hi @Aleyr @joeldesantos great work. Great work on coding that GUI. I've been testing the build function on my GNU/Linux system (Debian 9) this morning an here are the issues I've noticed:

-  `python3-tk` is not installed by default (it should be listed as a dependency),
- "skip existing files" should be `false` by default,
- the generated command line fails if one of the file path contains spaces, maybe file paths should be protected by quotes,
- the same problem affects the build button (no build, probably because of the spaces)

```sh
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "/tmp/pack/EverDrive-Packs-Lists-Database/buildframe.py", line 110, in <lambda>
    command=lambda: self.click_build()
  File "/tmp/pack/EverDrive-Packs-Lists-Database/buildframe.py", line 171, in click_build
    self.disable_components()
  File "/tmp/pack/EverDrive-Packs-Lists-Database/buildframe.py", line 123, in disable_components
    [self.clear_btn, self.build_btn])
  File "/tmp/pack/EverDrive-Packs-Lists-Database/buildframe.py", line 127, in change_state
    component.config(state=state)
AttributeError: 'NoneType' object has no attribute 'config'
```

**Comment by Aleyr** [comment]
@frederic-mahe You are correct tkinter is only included in Windows and Mac versions of Python, so it is a dependency for *nix distributions.

- I will add the python3-tk dependency on the Readme
- I have set the "skip existing files" to false by default
- My mistake on this part I did add the quotes for the parse but nor for the build, I have added the quotes
- Same issue as above

Also when fixing this issues above, I made a change to make sure paths are portable still need to test it out, will reply back when I finish that.

**Comment by frederic-mahe** [comment]
@Aleyr I ran a few test this morning, and the GUI seems to work perfectly. Great work!

Now, would you mind if we were to keep your GUI separated from this repository? I don't feel comfortable maintaining a GUI I did not write. Our README already points toward your repository, and @SmokeMonsterPacks and I could keep recommending to people who don't like CLI to use your GUI instead. A video tutorial could be made, maybe? :-)

The parse and build scripts are stable now, and basically, you'd only have to keep in sync with README changes (provided that you eliminate the SMDB files from your repository, but that's up to you). And you'd need to open up issue submission on your repository too.

**Comment by frederic-mahe** [comment]
@Aleyr sounds good! Please send a new pull request containing the `--new_line` parameter and the print function. Feel free to make PEP-related corrections too.

**Comment by Aleyr** [comment]
@frederic-mahe There are a lot of PEP changes, my IDE points them out and my OCD just makes me correct them, so I'll first just send the changes so that you can check them out clearly, then I can send a second one with the PEP changes if you want.

**Comment by frederic-mahe** [comment]
@Aleyr I normally use flake to detect PEP violations. My scripts were clean at first, but they seemed to have drifted away from PEP style with the functionalities and external contributions pilling up. Please, send a PEP commit, I'll see if its too much or not.

**Comment by frederic-mahe** [comment]
Diff looks good. I am going to run a few tests now.

**Comment by Aleyr** [comment]
@frederic-mahe Thanks. The new repo for the UI is https://github.com/Aleyr/EverDrive-Packs-Lists-Database-UI, already changed into the README.md file. I'm implementing a dialog to setup the scripts paths if my code is not on the same location.

**Pull request merged**
