### PR TITLE
N64: Added Super Luigi 64 (hack) v2.0.z64

### PR DESCRIPTION
**Pull request by pierreadrien**
Hey,

Should we add the 2.0 version of the Super Luigi 64 hack? Tested OK on my EverDrive X7.

More infos: https://mario64hacks.fandom.com/wiki/Super_Luigi_64
Patch: https://archive.org/details/sl6420

Cheers!

### CODE REVIEW

**Comment by Drakonas** [comment]
Before we accept this, I'll test on my 64Drive. If it works, it'd probably be better to add it to the main Hacks folder, not untested.

**Comment by pierreadrien** [comment]
> Before we accept this, I'll test on my 64Drive. If it works, it'd probably be better to add it to the main Hacks folder, not untested.

Alright thanks. Let's see how it goes for you.

**Comment by Drakonas** [comment]
Works fine. I'd probably cancel this PR and make a new one, placing it in the proper directory.

Screenshot

**Comment by Drakonas** [comment]
Or you can add another commit and push it to move the rom to the main Hacks folder I suppose. :P

**Comment by pierreadrien** [comment]
> Or you can add another commit and push it to move the rom to the main Hacks folder I suppose. :P

What I just did ;)

Thanks!

**Pull request merged**
