### PR TITLE
Mega Everdrive SMDB -- Clean up of 32X ROMs

### PR DESCRIPTION
**Pull request by eguevaralopez**
Changes done:

- Removed a redundant Super Skidmarks ROM from "4 Game Series"
- Renamed folders inside "2 Europe - A-Z"
- Moved european 32X games from inside "2 Europe - A-Z" to "3 Sega 32X"
- Reorganized 32X section based on No-Intro DAT file, this means renaming the ROMs and adding a lot of betas and protos.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
@eguevaralopez Provided that you've used No-Intro names when renaming the 32X entries (I cannot check that where I am), I am ok with all your changes.

@SmokeMonsterPacks @tjanas what do you think of moving european 32X games from inside `2 Europe - A-Z` to a `3 Sega 32X/2 Europe - A-Z`, alongside the already present `3 Sega 32X/1 US - A-Z` and `3 Sega 32X/2 Japan A-Z`

**Comment by SmokeMonsterPacks** [comment]
Yes, good call to move it there. I think that is an artifact of the way I organized things long ago when PAL and NTSC were two different lists completely.

**Comment by eguevaralopez** [comment]
I have a question concerning file organization that I thought I could ask here to use as an example. When I prepared this pull request, I filled up regions as follows: USA, Europe, Japan. I.e.;

- ROMs tagged `(World)`, `(USA)`, and `(USA, something)` were added to USA. The last tag often includes `(USA, Europe)` and `(Japan, USA)`;
- ROMs tagged `(Europe)` and `(Europe, something)` were added to Europe, **EXCEPT** those that were already added to USA in previous step. So, no ROMs tagged `(USA, Europe)` will be found here, but ROMs tagged `(Japan, Europe)` can be found here if they exist.
- ROMs tagged `(Japan)` and `(Japan, something)` were added to Japan, EXCEPT those already added to USA or Europe in previous steps.

This effectively trims down the amount of copies in each folder, and looking at the files present in the 32X folders it appears this is how it was organized to begin with.

My question is: is this the correct way to go about organizing the folders, or should Europe and Japan *also* include tags like `(USA, Europe)` or `(Japan, USA)` (in essence copying ROMs to those folders)? Or put another way, should each folder only remove the other "pure" tags, but allow mixed tags—`(Japan, USA)` ok in `2 Japan - A-Z` for example, but not `(USA)` or `(Europe)`?

I ask because I want to spruce up the Mega EverDrive SMDB, but I notice repeats in the Europe and Japanese folders so I don't know how to proceed.

**Comment by tjanas** [comment]
Great question, I have wondered the same. My understanding and practice is the same as yours (anything rom tagged with World or USA added to USA) , although if a rom was tagged as `(Japan, Europe)`, I would probably place it only in the Japan subdirectory and not in Europe. 

Currently, these rules aren't applied here; ;I see plenty of `(Japan, Europe)` roms have copies in Japan and Europe directories, and `(Japan, USA)` roms in both Japan and USA directories.

**Comment by eguevaralopez** [comment]
> Great question, I have wondered the same. My understanding and practice is the same as yours (anything rom tagged with World or USA added to USA) , although if a rom was tagged as `(Japan, Europe)`, I would probably place it only in the Japan subdirectory and not in Europe.

I do the same in the romsets I prepare at home, I give preference to NTSC regions instead of giving preference to English language. Of course, I'm from an NTSC region so I prefer *not patching* when possible, especially now that flashcarts can switch regions without modding.

> Currently, these rules aren't applied here; ;I see plenty of `(Japan, Europe)` roms have copies in Japan and Europe directories, and `(Japan, USA)` roms in both Japan and USA directories.

I can see arguments for both: if done like I did with this pull request, then the size would be trimmed down. This is negligible for the 32x set, but maybe a bit more noticeable with the Mega Drive set. If done the other I described, only excluding "pure" tags then its a snapshot of what a console of a given region can play without changing region (except not really, because not all games are region locked).

I'll wait for input before working further on the Mega EverDrive SMDB cleanup.

**Comment by eguevaralopez** [comment]
> 
> 
> I have a question concerning file organization that I thought I could ask here to use as an example. When I prepared this pull request, I filled up regions as follows: USA, Europe, Japan. I.e.;
> 
>     * ROMs tagged `(World)`, `(USA)`, and `(USA, something)` were added to USA. The last tag often includes `(USA, Europe)` and `(Japan, USA)`;
> 
>     * ROMs tagged `(Europe)` and `(Europe, something)` were added to Europe, **EXCEPT** those that were already added to USA in previous step. So, no ROMs tagged `(USA, Europe)` will be found here, but ROMs tagged `(Japan, Europe)` can be found here if they exist.
> 
>     * ROMs tagged `(Japan)` and `(Japan, something)` were added to Japan, EXCEPT those already added to USA or Europe in previous steps.
> 
> 
> This effectively trims down the amount of copies in each folder, and looking at the files present in the 32X folders it appears this is how it was organized to begin with.
> 
> My question is: is this the correct way to go about organizing the folders, or should Europe and Japan _also_ include tags like `(USA, Europe)` or `(Japan, USA)` (in essence copying ROMs to those folders)? Or put another way, should each folder only remove the other "pure" tags, but allow mixed tags—`(Japan, USA)` ok in `2 Japan - A-Z` for example, but `(USA)` or `(Europe)` not ok in `2 Japan - A-Z`?
> 
> I ask because I want to spruce up the Mega EverDrive SMDB, but I notice repeats in the Europe and Japanese folders so I don't know how to proceed.

@frederic-mahe @SmokeMonsterPacks could I get some input on this?

**Comment by frederic-mahe** [comment]
@eguevaralopez I am inclined to keep a US-centric parsimonious approach:

- if a given game exists in different world regions and if the PAL-, NTSC-U or NTSC-J ROMs are different (i.e. hash values are different), then a copy of each ROM should appear in the concerned USA, Japan or Europe folders,
- when the regional releases are identical, for instance the same exact ROM distributed in both USA and Japan (same hash value), then keep a copy only in the USA folder.

What matters is that files are correctly labeled: `(World)`, `(USA)`, `(USA, something)`,  `(Europe)`, `(Europe, something)`, ...

If we have that info then I can write a script to remove duplicated entries (US-centric parsimonious approach), or to duplicate entries (regional _completionist_ approach). That should not be difficult, so don't let that issue block you.

**Comment by eguevaralopez** [comment]
> @eguevaralopez I am inclined to keep a US-centric parsimonious approach:
> 
>     * if a given game exists in different world regions and if the PAL-, NTSC-U or NTSC-J ROMs are different (i.e. hash values are different), then a copy of each ROM should appear in the concerned USA, Japan or Europe folders,
> 
>     * when the regional releases are identical, for instance the same exact ROM distributed in both USA and Japan (same hash value), then keep a copy only in the USA folder.

@frederic-mahe alright. Supposing I use the same approach for all regions, which region should get "second priority"? E.g, `Arrow Flash (Japan, Europe).md` should appear only in Europe folder or only in Japan folder?

**Comment by frederic-mahe** [comment]
I'd say Japan.

If I were to write a script to search for duplicated entries, I'd expected to find `Arrow Flash (Japan, Europe).md` in `Japan` and I would remove the copy in `Europe`, if any. For `Unlikely (Europe, Japan).md` I'd keep the copy in `Europe` and remove the one in `Japan`.

**Comment by tjanas** [comment]
I agree that `Arrow Flash (Japan, Europe)` should only be in the `Japan` directory, and removed from the `Europe` directory. And `(Japan, USA)` should only be in the `USA` directory.

For entries like `Mega Bomberman (Europe, Korea)` and `Mega Games 3 (Europe, Asia)`, I would recommend they are placed in `Europe`.

I don't see any cases in no-intro for Genesis where the region is `(Europe, Japan)`.

**Pull request merged**
