### PR TITLE
NES: Update N8 & PowerPak SMDB

### PR DESCRIPTION
**Pull request by maniac79**
**Next big update.**

Added four games to 3 Famicom Disk System/1 FDS Japan - A-Z/ which seem to belong here but were previously only found in /Game Collection Series/*.
Family Computer Golf Japan Course (Japan).fds
Family Computer Golf Special Course (Japan) (Prize Card).fds
Family Computer Golf Tournament - Japan Course (Japan) (Prize Card).fds
Family Computer Golf U.S. Course (Japan).fds

Added new game:
3 Nintendo Switch/Steins;Gate (USA) (Nintendo Switch).nes
(Supposedly runs on real hardware, was released on Switch.)

Rebuilt/restructured 4 Betas, Prototypes, Revisions/* with latest No-Intro specs, added missing files from previous pack

Rebuilt/restructured 5 Tools & Service Test Carts/ with latest No-Intro specs, added missing files from previous pack

@Frédéric: More details in eMail.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
thanks @maniac79 I am working on a local copy of your patch:
```
# addition
      6 EverDrive N8/3 Famicom Disk System
      1 EverDrive N8/3 Nintendo Switch
    710 EverDrive N8/4 Betas, Prototypes, Revisions
     10 EverDrive N8/5 Tools & Service Test Carts
# deletion
    521 EverDrive N8/4 Betas, Prototypes, Revisions
      8 EverDrive N8/5 Tools & Service Test Carts
```
I am going to pull in your 6 changes to the Famicom Disk System, but let's agree that @tjanas 's work on the Famicom Disk System will soon replace what's currently in N8.

Regarding `3 Nintendo Switch/Steins;Gate (USA) (Nintendo Switch).nes` I think for now we should put it in `4 Betas, Prototypes, Revisions`, along with ROMs such as _GameCube Edition_. If Nintendo starts releasing new NES games, playable on real hardware, then we can revise and create a dedicated top-level folder. If you agree, please make the change and submit a commit to your pull request.

> Rebuilt/restructured 5 Tools & Service Test Carts/ with latest No-Intro specs, added missing files from previous pack

This service ROM is removed by your patch, is this intentional? `Unlicense HVC Controller Test (PD).nes`


`4 Betas, Prototypes, Revisions/Competitions/Nintendo World Championships 1990 (USA) (Competition Cart).nes`

@tjanas @SmokeMonsterPacks @tjstogy any idea where to place this game?

**Comment by maniac79** [comment]
> I am going to pull in your 6 changes to the Famicom Disk System, but let's agree that @tjanas 's work on the Famicom Disk System will soon replace what's currently in N8.

Of course! :) Looking forward to it.

> Regarding `3 Nintendo Switch/Steins;Gate (USA) (Nintendo Switch).nes` I think for now we should put it in `4 Betas, Prototypes, Revisions`, along with ROMs such as _GameCube Edition_. If Nintendo starts releasing new NES games, playable on real hardware, then we can revise and create a dedicated top-level folder. If you agree, please make the change and submit a commit to your pull request.

But it's not a Beta, Prototype or Revision of any previous game. It's a completely new game.
The Gamecube* folders are subfolders of the Revisions folders:
4 Betas, Prototypes, Revisions/Revisions A-Z/1 US/Gamecube, Virtual Console/
4 Betas, Prototypes, Revisions/Revisions A-Z/2 PAL/Gamecube, Virtual Console/
4 Betas, Prototypes, Revisions/Revisions A-Z/3 Japan/
I don't feel putting that here would be intuitive.

> This service ROM is removed by your patch, is this intentional? `Unlicense HVC Controller Test (PD).nes`

Well spotted! I'll re-add it.

**Comment by tjanas** [comment]
[Steins;Gate (USA) (Nintendo Switch).nes](https://datomatic.no-intro.org/?page=show_record&s=45&n=2858) seems more like an unlicensed game rather than a revision, because like @maniac79 mentioned, it is a new game.

@frederic-mahe I would place [Nintendo World Championships](https://datomatic.no-intro.org/?page=show_record&s=45&n=1584) in `1 US - G-Q/` since it was a real cart produced by Nintendo.

**Comment by frederic-mahe** [comment]
> @frederic-mahe I would place Nintendo World Championships in 1 US - G-Q/ since it was a real cart produced by Nintendo.

It was not for sale though, more like an internal prototype Nintendo used for one-time events. What about placing it in `Prototypes A - Z/`?

> Steins;Gate (USA) (Nintendo Switch).nes seems more like an unlicensed game rather than a revision, because like @maniac79 mentioned, it is a new game.

Unlicensed is a good idea, but I am inclined to put it aside for now. We can discuss its fate in #236 @maniac79 would you be ok to remove that entry from your patch for now? 

I went through your changes to `4 Betas, Prototypes, Revisions`, your new organization seems ok to me:
```
4 Betas, Prototypes, Revisions/Betas A-Z
4 Betas, Prototypes, Revisions/Competitions
4 Betas, Prototypes, Revisions/Prototypes A-Z
4 Betas, Prototypes, Revisions/Revisions A-Z/1 US
4 Betas, Prototypes, Revisions/Revisions A-Z/1 US/Gamecube, Virtual Console
4 Betas, Prototypes, Revisions/Revisions A-Z/2 PAL
4 Betas, Prototypes, Revisions/Revisions A-Z/2 PAL/Gamecube, Virtual Console
4 Betas, Prototypes, Revisions/Revisions A-Z/3 Japan
4 Betas, Prototypes, Revisions/Revisions A-Z/3 Japan/Gamecube, Virtual Console
4 Betas, Prototypes, Revisions/Revisions A-Z/4 Samples
4 Betas, Prototypes, Revisions/Revisions A-Z/4 Unlicensed
```

**Comment by maniac79** [comment]
> It was not for sale though, more like an internal prototype Nintendo used for one-time events. What about placing it in `Prototypes A - Z/`?

I agree. If @tjanas agrees too, I'll do it quickly.

> Unlicensed is a good idea, but I am inclined to put it aside for now. We can discuss its fate in #236 @maniac79 would you be ok to remove that entry from your patch for now?

Removed temporarily.

**Comment by tjanas** [comment]
I am OK with it being treated as a prototype.

**Comment by maniac79** [comment]
Update committed. :)

**Comment by frederic-mahe** [comment]
@maniac79 it turns out I was wrong, you are pushing new entries corresponding to ROMs with NES2.0 headers. The bad news is that these do not seem to work on the Everdrive N8.

So here is what I propose to do: I am going to merge your pull request, then create a new branch just for NES stuff, then go back to master and restore a non-NES2.0 SMDB. Your next pull requests will have to be against that new branch. That way we can continue to pull in your changes, and the master SMDB is not in a broken state.

Let me know if you have difficulties submitting pull requests against another branch.

**Comment by frederic-mahe** [comment]
new branch is called NES_update

**Comment by maniac79** [comment]
> @maniac79 it turns out I was wrong, you are pushing new entries corresponding to ROMs with NES2.0 headers. The bad news is that these do not seem to work on the Everdrive N8.

Have you verified that they are not working with the N8?
I playtested some games with my N8 to make sure and everything I threw at it seemed to work fine. I remember at least DuckTales ran fine. But I forgot which other games I tested.
I'll run some tests tomorrow.

**Comment by tjanas** [comment]
It was confirmed they will not run on an Nt Mini. Also, need to check PowerPak compatibility (I don’t have one).

**Comment by tjanas** [comment]
Also, I checked the NES2.0 header for SMB3 Rev. 1 and it was not correct according to the header database.

**Comment by frederic-mahe** [comment]
There are currently issues and uncertainties regarding the support of NES2.0 headers on the Nt Mini, Everdrive N8 and PowerPak. We will see how things evolve, but in the meantime we should continue to merge your changes @maniac79 

Once we will have a clean and up-to-date NES pack, we can use [Great Hierophant's database](https://nerdlypleasures.blogspot.com/2020/04/the-nes-and-famicom-accurate-cartridge.html) and [Rysha's script](https://github.com/Kitrinx/NES_Header_Repair) to fix headers automatically, either towards pure NES2.0, or towards a slightly modified NES2.0 compatible with the devices mentioned above. Great Hierophant wrote:
```
Change the lines :
        header[14] = (miscrom & 0x3)
        header[15] = (expansion & 0x3F)
to :
       header[14] = (miscrom & 0)
       header[15] = (expansion & 0)
Run the script and you can have your Nt Mini 2.0 compatible ROMs.
```

**Pull request merged**
